### ISSUE TITLE
Chapter 1 error

### ISSUE THREAD

**Issue by evelynmitchell** [hintjens/psychopathcode#8]
"Women need tools as well as men, yet are unlikely to be toolmakers."

This is an unsupported claim. You have no evidence of the gender of flint knappers. Also you have no evidence of the use or manufacture of tools which are not found in archaeological digs due to the material they are made of.

**Comment by hintjens** [comment]
True we cannot talk about non-permanent tools. As for gender and toolmaking, it's a claim which fits the ample evidence (we have zero cultures where women are the tool makers). I'm not going to argue such points... there are many in the book and you can add "for the sake of argument" if you like, or reject the arguments that follow, as you prefer.
